const stockSymbols = {
    'atvi': 'activision blizzard',
    'atvi': 'activision',
    'adbe': 'adobe',
    'amd': 'amd',
    'amd': 'advanced micro devices',
    'alxn': 'alexion',
    'alxn': 'alexion pharmaceutics',
    'algn': 'align',
    'googl': 'alphabet',
    'googl': 'google',
    'amzn': 'amazon',
    'aal': 'american airlines',
    'amgn': 'amgen',
    'adi': 'analog devices',
    'anss': 'ansys',
    'aapl': 'apple',
    'amat': 'aplied materials',
    'asml': 'asml',
    'adsk': 'autodesk',
    'adp': 'automatic data processing',
    'bidu': 'baidu',
    'biib': 'biogen',
    'bmrn': 'biomarin',
    'bkng': 'booking',
    'avgo': 'broadcom',
    'cdns': 'cadence design',
    'cdw': 'cdw',
    'cern': 'cerner',
    'chtr': 'charter',
    'chtr': 'charter comunications',
    'chkp': 'check point',
    'ctas': 'cintas',
    'csco': 'cisco',
    'ctxs': 'citrix',
    'ctsh': 'cognizart',
    'cmcsa': 'comcast',
    'cprt': 'copart',
    'csgp': 'costar',
    'cost': 'costco wholesale',
    'csx': 'csx',
    'dltr': 'dollar tree',
    'ebay': 'ebay',
    'ea': 'electronic arts',
    'exc': 'exelon',
    'expe': 'expedia',
    'fb': 'facebook',
    'fast': 'fastenal',
    'fisv': 'fiserv',
    'fox': 'fox corporation',
    'gild': 'gilead',
    'idxx': 'idexx',
    'ilmn': 'illuminia',
    'incy': 'incyte',
    'intc': 'intel',
    'isrg': 'intuitive',
    'jd': 'jd.com',
    'klac': 'kla',
    'khc': 'kraft heinz',
    'lrcx': 'lam research',
    'lbtya': 'liberty globa',
    'lulu': 'lululemon',
    'mar': 'marriot',
    'mxim': 'maxim',
    'meli': 'mercado libre',
    'mchp': 'microchip',
    'mu': 'micron',
    'msft': 'microsoft',
    'mdlz': 'mondelez',
    'mnst': 'monster',
    'ntap': 'netapp',
    'ntes': 'netease',
    'nflx': 'netflix',
    'nvda': 'nvidia',
    'nxpi': 'nxp semiconductors',
    'orly': "o'reilly",
    'pcar': 'paccar',
    'payx': 'paychex',
    'pypl': 'paypal',
    'pep': 'pepsi',
    'qcom': 'qualcom',
    'regn': 'regeneron',
    'rost': 'ross stores',
    'sgen': 'seattle generics',
    'siri': 'sirius xm radio',
    'splk': 'splunk',
    'sbux': 'starbucks',
    'snps': 'synopsys',
    'tmus': 't-mobile',
    'ttwo': 'take-two',
    'tsla': 'tesla',
    'txn': 'texas instruments',
    'tcom': 'trip.com',
    'ulta': 'ulta beauty',
    'ual': 'united airlines',
    'vrsn': 'verisign',
    'vrsk': 'verisk analytics',
    'vrtx': 'vertex',
    'wba': 'walgreen boots',
    'wday': 'workday',
    'wdc': 'western digital',
    'wltw': 'willis towers watson',
    'xel': 'xcel energy',
    'xlnx': 'xilinx'
}